Core: Add capability to check array of inputs
jquery-validation/jquery-validation pull request #2431
Opened 2022-07-01 02:58 UTC by ridea-co

#### Description
Add capability to check array of inputs.
Basically a copy & paste code from #2000 with checkbox/radio check

2022-07-01 13:09 UTC, bytestream commented
What's the checkbox/radio check for?

2022-07-02 05:00 UTC, ridea-co commented
The reason of filtering out radios and checkboxes is that when you have multiple radio buttons or checkboxes with same name, I believe user really expecting only one of then to be selected instead all of them have to be selected.  So for those 2 types of inputs, they fall back to the original program logic thus error message should display correctly.

2022-07-05 13:31 UTC, ridea-co commented
Hi, just wondering if everything look good to be merged in?

2023-11-30 09:54 UTC, Seb33300 requested changes
Please fix the requested change

2025-01-24 22:24 UTC, bytestream commented
Closing in favor of #2498 - please comment on that PR if it doesn't work / match the behaviour of this PR.

2025-01-24 22:24 UTC, closed without merging